name: Story Development
on: 
  push:
    branches-ignore:
      - master
jobs:
  make:
    runs-on: ubuntu-16.04
    name: Make
    steps:
    - name: Checkout
      uses: actions/checkout@v1      
    - name: Make   
      run:  docker run -v ~/am/github/Onboard-SDK/:/github/workspace -t docker.cloudsmith.io/automodality/trial/amros-base /github/workspace/make.sh

