name: Story Development
on: 
  push:
    branches-ignore:
      - master
jobs:
  make:
    runs-on: ubuntu-16.04
    name: Make
    steps:
    - name: Checkout
      uses: actions/checkout@v1      
    - name: Make   
      uses: AutoModality/action-make-ros@v1.0.0
      with:
          cmake-args: -DADVANCED_SENSING:BOOL=ON
          make-args: djiosdk-core

